export type CesiumKindTarget = {
  backend: string;
  target: string;
  status: string;
};

export const CESIUM_KIND_TARGETS: Record<string, CesiumKindTarget> = {
  point: { backend: "entity", target: "PointGraphics", status: "implemented" },
  billboard: { backend: "entity", target: "BillboardGraphics", status: "implemented" },
  label: { backend: "entity", target: "LabelGraphics", status: "implemented" },
  model: { backend: "entity", target: "ModelGraphics", status: "implemented" },
  track: { backend: "entity", target: "Entity + SampledPositionProperty + optional PathGraphics", status: "implemented" },
  path: { backend: "entity", target: "PolylineGraphics or PathGraphics", status: "implemented" },
  polyline: { backend: "entity", target: "PolylineGraphics", status: "implemented" },
  polygon: { backend: "entity", target: "PolygonGraphics", status: "implemented" },
  rectangle: { backend: "entity", target: "RectangleGraphics", status: "implemented" },
  ellipse: { backend: "entity", target: "EllipseGraphics", status: "implemented" },
  circle: { backend: "entity", target: "EllipseGraphics with equal axes", status: "implemented" },
  box: { backend: "entity", target: "BoxGraphics", status: "implemented" },
  cylinder: { backend: "entity", target: "CylinderGraphics", status: "implemented" },
  cone: { backend: "entity", target: "CylinderGraphics with topRadius = 0", status: "implemented" },
  ellipsoid: { backend: "entity", target: "EllipsoidGraphics", status: "implemented" },
  sphere: { backend: "entity", target: "EllipsoidGraphics with equal radii", status: "implemented" },
  hemisphere: { backend: "primitive", target: "Primitive + generated spherical wedge mesh; Entity ellipsoid fallback available", status: "implemented" },
  sphericalCap: { backend: "primitive", target: "Primitive + generated spherical cap mesh; Entity ellipsoid fallback available", status: "implemented" },
  sectorVolume: { backend: "primitive", target: "Primitive + generated spherical sector-volume mesh; Entity ellipsoid fallback available", status: "implemented" },
  keyhole: { backend: "primitive", target: "Primitive + generated spherical shell/wedge mesh; ion sensor backend can supersede", status: "implemented" },
  conicSensor: { backend: "primitive", target: "Opaque sensor swath placeholder", status: "implemented" },
  rectangularSensor: { backend: "primitive", target: "Opaque sensor swath placeholder", status: "implemented" },
  customPatternSensor: { backend: "primitive", target: "Opaque sensor swath placeholder", status: "implemented" },
  wall: { backend: "entity", target: "WallGraphics", status: "implemented" },
  corridor: { backend: "entity", target: "CorridorGraphics", status: "implemented" },
  polylineVolume: { backend: "entity", target: "PolylineVolumeGraphics", status: "implemented" },
  plane: { backend: "entity", target: "PlaneGraphics", status: "implemented" },
  sector2d: { backend: "entity", target: "PolygonGraphics generated from sector parameters", status: "implemented" },
  bearingFan: { backend: "entity", target: "PolygonGraphics generated from sector parameters", status: "implemented" },
  frustum: { backend: "primitive", target: "Primitive + generated rectangular frustum mesh", status: "implemented" },
  fan: { backend: "entity", target: "PolygonGraphics fallback; ion FanGraphics preferred later", status: "implemented" },
  tileset: { backend: "primitive", target: "Cesium3DTileset", status: "implemented" },
  velocityVector: { backend: "entity", target: "CallbackProperty PolylineGraphics", status: "implemented" },
  accelerationVector: { backend: "entity", target: "CallbackProperty PolylineGraphics", status: "implemented" },
  vector: { backend: "entity", target: "CallbackProperty PolylineGraphics", status: "implemented" },
  bodyAxes: { backend: "entity", target: "three CallbackProperty PolylineGraphics objects", status: "implemented" },
  principalAxes: { backend: "entity", target: "covariance eigenvector-derived CallbackProperty PolylineGraphics", status: "implemented" },
  lineOfSight: { backend: "entity", target: "CallbackProperty PolylineGraphics", status: "implemented" },
  relativeLine: { backend: "entity", target: "CallbackProperty PolylineGraphics", status: "implemented" },
  interceptLine: { backend: "entity", target: "CallbackProperty PolylineGraphics", status: "implemented" },
  rangeRing: { backend: "entity", target: "EllipseGraphics outline", status: "implemented" },
  uncertaintyEllipsoid: { backend: "entity", target: "EllipsoidGraphics", status: "implemented" },
  covarianceEllipse: { backend: "entity", target: "EllipseGraphics", status: "implemented" },
  particleSystem: { backend: "primitive", target: "ParticleSystem", status: "implemented" },
  voxel: { backend: "primitive", target: "VoxelPrimitive", status: "implemented" },
  terrainSurface: { backend: "scene", target: "Opaque runtime attachment placeholder", status: "implemented" },
  customMesh: { backend: "primitive", target: "Opaque runtime mesh placeholder", status: "implemented" },
  clippingPolygon: { backend: "scene", target: "ClippingPolygonCollection", status: "implemented" },
  clippingPlane: { backend: "scene", target: "ClippingPlaneCollection", status: "implemented" },
  classificationVolume: { backend: "primitive", target: "ClassificationPrimitive", status: "implemented" },
  classificationPrimitive: { backend: "primitive", target: "ClassificationPrimitive", status: "implemented" },
  customPrimitive: { backend: "primitive", target: "Primitive + GeometryInstance generated from explicit mesh", status: "implemented" },
  primitiveMesh: { backend: "primitive", target: "Primitive + GeometryInstance generated from explicit mesh", status: "implemented" },
  postProcessStage: { backend: "scene", target: "PostProcessStage", status: "implemented" },
  composite: { backend: "scene", target: "Composite attachment placeholder", status: "implemented" },
  atmosphere: { backend: "scene", target: "Atmosphere settings", status: "implemented" },
  imageryLayer: { backend: "scene", target: "ImageryLayer/provider", status: "implemented" },
  terrain: { backend: "scene", target: "TerrainProvider/Terrain", status: "implemented" },
  czmlDataSource: { backend: "dataSource", target: "CzmlDataSource", status: "implemented" },
  geoJsonDataSource: { backend: "dataSource", target: "GeoJsonDataSource", status: "implemented" },
  kmlDataSource: { backend: "dataSource", target: "KmlDataSource", status: "implemented" },
  dataSource: { backend: "dataSource", target: "DataSource", status: "implemented" },
  tilesetStyle: { backend: "scene", target: "Cesium3DTileStyle", status: "implemented" },
  customShader: { backend: "scene", target: "CustomShader", status: "implemented" },
  cloudCollection: { backend: "primitive", target: "CloudCollection", status: "implemented" },
  skyBox: { backend: "scene", target: "SkyBox", status: "implemented" },
  groundPolyline: { backend: "primitive", target: "GroundPolylinePrimitive", status: "implemented" },
  groundPrimitive: { backend: "primitive", target: "GroundPrimitive", status: "implemented" },
  panorama: { backend: "primitive", target: "inside-out sphere/cube or imagery adapter", status: "implemented" },
  videoPlane: { backend: "entity", target: "PlaneGraphics or RectangleGraphics with video material", status: "implemented" },
  cameraView: { backend: "scene", target: "viewer camera control metadata", status: "implemented" },
  debugInspector: { backend: "scene", target: "CesiumInspector / debug flags", status: "implemented" }
};
